/**
 * Customer was generated by GFS
 */

package vo.customer
{
	import vo.company.CompanyVO
	import vo.person.PersonVO

	[Bindable]	
	[RemoteClass(alias='Customer')]
	public class CustomerVO extends PersonVO
	{
		//Properties
		public var company:CompanyVO;
	}
}