/**
 * Person was generated by GFS
 */

package vo.person
{
	import mx.collections.ArrayCollection

	[Bindable]	
	[RemoteClass(alias='Person')]
	public class PersonVO 
	{
		//Identity
		public var id:Object;
		public var version:Object;
		//Properties
		public var addresses:ArrayCollection;
		public var email:String;
		public var firstName:String;
		public var lastName:String;
		public var personalPhoto:String;
	}
}