<%/**
 * Copyright 2009 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * 
 * @author Ezequiel Martin Apfel
 * @since 01-Feb-2009
 */%>
package vo.${domainClass.propertyName}
{
<%//Generate Import
import org.cubika.labs.scaffolding.utils.FlexScaffoldingUtils as FSU

def props = FSU.getPropertiesWithoutIdentity(domainClass)
props.each
{
		def imp = FSU.getImport4AS3(it)
		if(imp && imp != "")
			println "	${imp}"
}
props = FSU.getPropertiesWithIdentity(domainClass)
%>
	/**
	 * ${className} was generated by GFS
	 */
	[Bindable]	
	[RemoteClass(alias='${className}')]
	public class ${className}VO
	{
		//Identity
<%
props.each
{
	if (it.isIdentity() || it.name == "version")
		println "		public var ${it.name}:${FSU.getClass4AS3(it)};"
}%>		//Properties
<%
props.each
{
	if (!it.isIdentity() && it.name != "version")
	{
		def property = FSU.getClass4AS3(it);
		if (property)
			println "		public var ${it.name}:${property};"
	}
}%>	}
}