/**
 * Address was generated by GFS
 */

package vo.address
{

	[Bindable]	
	[RemoteClass(alias='Address')]
	public class AddressVO 
	{
		//Identity
		public var id:Object;
		public var version:Object;
		//Properties
		public var street:String;
		public var zip:String;
	}
}