
package vo.phone
{

	/**
	 * Phone was generated by GFS
	 */
	[Bindable]	
	[RemoteClass(alias='Phone')]
	public class PhoneVO
	{
		//Identity
		public var id:Object;
		public var version:Object;
		//Properties
		public var number:String;
		public var type:String;
	}
}