
package vo.customer
{
	import mx.collections.ArrayCollection
	import vo.company.CompanyVO
	import vo.phone.PhoneVO

	/**
	 * Customer was generated by GFS
	 */
	[Bindable]	
	[RemoteClass(alias='Customer')]
	public class CustomerVO
	{
		//Identity
		public var id:Object;
		public var version:Object;
		//Properties
		public var addresses:ArrayCollection;
		public var age:int;
		public var blog:String;
		public var company:CompanyVO;
		public var dateOfBirth:Date;
		public var email:String;
		public var enabled:Boolean = true;
		public var firstName:String;
		public var lastName:String;
		public var maritalStatus:String;
		public var phone:PhoneVO;
	}
}