
package vo.address
{

	/**
	 * Address was generated by GFS
	 */
	[Bindable]	
	[RemoteClass(alias='Address')]
	public class AddressVO
	{
		//Identity
		public var id:Object;
		public var version:Object;
		//Properties
		public var number:int;
		public var observation:String;
		public var street:String;
		public var zip:String;
	}
}