/**
 * Company was generated by GFS
 */

package vo.company
{

	[Bindable]	
	[RemoteClass(alias='Company')]
	public class CompanyVO 
	{
		//Identity
		public var id:Object;
		public var version:Object;
		//Properties
		public var description:String;
		public var logo:String;
		public var name:String;
	}
}